general {
  hide_cursor = true
}

background {
  monitor =
  path = screenshot
  blur_passes = 2
  blur_size = 4
  noise = 0.0117
  contrast = 0.9
  brightness = 0.45
}

label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = rgba(240, 240, 240, 1.0)
  font_size = 72
  font_family = Noto Sans
  position = 0, 100
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %d %B %Y"
  color = rgba(190, 190, 190, 1.0)
  font_size = 18
  font_family = Noto Sans
  position = 0, 35
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 280, 46
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.25
  outer_color = rgba(255, 255, 255, 0.32)
  inner_color = rgba(5, 5, 5, 0.62)
  font_color = rgba(240, 240, 240, 1.0)
  fade_on_empty = false
  placeholder_text =
  check_color = rgba(240, 240, 240, 1.0)
  fail_color = rgba(247, 118, 142, 1.0)
  position = 0, -70
  halign = center
  valign = center
}
