splash = false
ipc = true

wallpaper {
  monitor = HDMI-A-1
  path = ~/.dotfiles/wallpapers/current.jpg
  fit_mode = cover
}

wallpaper {
  monitor = eDP-1
  path = ~/.dotfiles/wallpapers/current.jpg
  fit_mode = cover
}
