font_family JetBrainsMono Nerd Font
font_size 11.5

background #050505
foreground #f0f0f0
background_opacity 0.72
dynamic_background_opacity yes

cursor #f0f0f0
cursor_text_color #050505
cursor_shape beam
cursor_blink_interval 0.5

selection_background #404040
selection_foreground #ffffff

window_padding_width 10
hide_window_decorations yes

scrollback_lines 10000
enable_audio_bell no
confirm_os_window_close 0

url_color #bfbfbf
url_style single

color0  #151515
color1  #e06c75
color2  #98c379
color3  #d19a66
color4  #a5a5a5
color5  #c678dd
color6  #8abeb7
color7  #d0d0d0

color8  #606060
color9  #e06c75
color10 #98c379
color11 #e5c07b
color12 #c0c0c0
color13 #c678dd
color14 #9ad0c2
color15 #ffffff
