-- ASUS TUF Gaming FX505DT GPUs detected read-only on 2026-08-30:
--   01:00.0 NVIDIA TU117M GeForce GTX 1650 Mobile / Max-Q
--   05:00.0 AMD Picasso/Raven 2 Radeon Vega Series / Vega Mobile Series
--
-- Persistent DRM paths detected:
--   NVIDIA card: /dev/dri/by-path/pci-0000:01:00.0-card
--   NVIDIA render: /dev/dri/by-path/pci-0000:01:00.0-render
--   AMD card:    /dev/dri/by-path/pci-0000:05:00.0-card
--   AMD render:  /dev/dri/by-path/pci-0000:05:00.0-render
--
-- AQ_DRM_DEVICES is intentionally disabled for the first Hyprland session.
--
-- Hyprland/Aquamarine expects AQ_DRM_DEVICES to be a colon-separated list, but
-- the PCI by-path names also contain colons. Do not concatenate these paths
-- directly. For now Hyprland will autodetect GPUs during the first session.
--
-- After confirming the first session and monitor wiring, decide whether to add
-- persistent DRM aliases for AMD/NVIDIA with udev rules in a separate reviewed
-- step.
--
-- Intended future order, once safe aliases exist:
--   AMD Vega first, NVIDIA GTX 1650 second.
-- Example only:
--   hl.env("AQ_DRM_DEVICES", "/dev/dri/amd-igpu:/dev/dri/nvidia-dgpu")

-- Do not add legacy NVIDIA variables here by habit. Revisit only if a concrete
-- issue appears and current Hyprland/Arch documentation still recommends it.
